"""
Static HTML site builder for Folio.

Generates a complete, self-contained static website:
  - site/index.html          (main knowledge base page)
  - site/articles/[id].html  (article detail pages)
  - site/category/[tag].html (category pages)
  - site/search.json         (Fuse.js search index)
  - site/assets/             (CSS/JS)
"""

from __future__ import annotations

import json
import logging
import re
import shutil
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from wesum.config import SiteConfig
from wesum.database import Article, Database

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# HTML Templates (inline — no external template files needed for static gen)
# ---------------------------------------------------------------------------

_TAILWIND_CDN = "https://cdn.tailwindcss.com"
_FUSE_CDN = "https://cdn.jsdelivr.net/npm/fuse.js@7.0.0/dist/fuse.min.js"

_HEAD_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}" class="">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="{description}">
  <title>{page_title} - {site_title}</title>
  <script src="{tailwind_cdn}"></script>
  <script>
    tailwind.config = {{
      darkMode: 'class',
      theme: {{
        extend: {{
          fontFamily: {{
            sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"PingFang SC"', '"Hiragino Sans GB"', '"Microsoft YaHei"', 'sans-serif'],
          }}
        }}
      }}
    }}
  </script>
  <style>
    .article-row:hover {{ background-color: rgba(99, 102, 241, 0.04); }}
    .dark .article-row:hover {{ background-color: rgba(99, 102, 241, 0.1); }}
    .tag-badge {{ display: inline-flex; align-items: center; }}
    .prose h2 {{ margin-top: 1.5rem; margin-bottom: 0.5rem; font-size: 1.1rem; font-weight: 600; }}
    .prose ul {{ margin-left: 1.5rem; list-style-type: disc; }}
    .prose blockquote {{ border-left: 3px solid #6366f1; padding-left: 1rem; color: #6b7280; font-style: italic; }}
    .highlight {{ background: rgba(250, 204, 21, 0.4); border-radius: 2px; padding: 0 2px; }}
    .dark .highlight {{ background: rgba(250, 204, 21, 0.2); }}
  </style>
</head>
<body class="bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100 min-h-screen transition-colors duration-200">
"""

_NAVBAR_TEMPLATE = """
  <nav class="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 sticky top-0 z-50 shadow-sm">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-14">
        <div class="flex items-center gap-6">
          <a href="{index_url}" class="flex items-center gap-2 font-bold text-indigo-600 dark:text-indigo-400 text-lg">
            <span>📚</span>
            <span>{site_title}</span>
          </a>
          <div class="hidden sm:flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400">
            <a href="{index_url}" class="hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">全部</a>
            {category_links}
          </div>
        </div>
        <div class="flex items-center gap-3">
          <div class="relative">
            <input type="search" id="search-input" placeholder="搜索文章..." 
              class="w-48 sm:w-64 px-3 py-1.5 text-sm bg-gray-100 dark:bg-gray-700 rounded-lg 
                     border border-transparent focus:outline-none focus:border-indigo-400 
                     focus:bg-white dark:focus:bg-gray-600 transition-all placeholder-gray-400">
            <div id="search-results" class="absolute right-0 top-full mt-1 w-80 bg-white dark:bg-gray-800 
                 rounded-lg shadow-lg border border-gray-200 dark:border-gray-700 hidden z-50 max-h-80 overflow-y-auto">
            </div>
          </div>
          <button id="theme-toggle" class="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors" title="切换主题">
            <span id="theme-icon">🌙</span>
          </button>
        </div>
      </div>
    </div>
  </nav>
"""

_FOOTER_TEMPLATE = """
  <footer class="mt-16 py-8 border-t border-gray-200 dark:border-gray-700 text-center text-sm text-gray-500 dark:text-gray-400">
    <p>Generated by <a href="https://github.com/yourusername/Folio" class="text-indigo-600 dark:text-indigo-400 hover:underline">Folio</a> · {generated_at}</p>
    <p class="mt-1">{stats_text}</p>
  </footer>
"""

_THEME_SCRIPT = """
<script>
  // Theme management
  const themeToggle = document.getElementById('theme-toggle');
  const themeIcon = document.getElementById('theme-icon');
  const html = document.documentElement;
  
  function getStoredTheme() {
    return localStorage.getItem('theme') || 'auto';
  }
  
  function applyTheme(theme) {
    if (theme === 'dark' || (theme === 'auto' && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      html.classList.add('dark');
      if (themeIcon) themeIcon.textContent = '☀️';
    } else {
      html.classList.remove('dark');
      if (themeIcon) themeIcon.textContent = '🌙';
    }
  }
  
  applyTheme(getStoredTheme());
  
  if (themeToggle) {
    themeToggle.addEventListener('click', () => {
      const isDark = html.classList.contains('dark');
      const newTheme = isDark ? 'light' : 'dark';
      localStorage.setItem('theme', newTheme);
      applyTheme(newTheme);
    });
  }
</script>
"""

_SEARCH_SCRIPT = """
<script src="{fuse_cdn}"></script>
<script>
let fuseInstance = null;
let searchData = null;

async function loadSearchData() {
  if (searchData) return searchData;
  try {
    const res = await fetch('{search_json_url}');
    searchData = await res.json();
    fuseInstance = new Fuse(searchData, {
      keys: [
        { name: 'title', weight: 0.4 },
        { name: 'summary', weight: 0.3 },
        { name: 'source', weight: 0.1 },
        { name: 'topic_tags', weight: 0.2 }
      ],
      threshold: 0.4,
      includeMatches: true,
      minMatchCharLength: 1
    });
  } catch(e) {
    console.warn('Search data load failed:', e);
  }
  return searchData;
}

const searchInput = document.getElementById('search-input');
const searchResults = document.getElementById('search-results');

if (searchInput) {
  searchInput.addEventListener('input', async (e) => {
    const query = e.target.value.trim();
    if (!query) {
      searchResults.classList.add('hidden');
      return;
    }
    
    await loadSearchData();
    if (!fuseInstance) return;
    
    const results = fuseInstance.search(query, { limit: 8 });
    
    if (results.length === 0) {
      searchResults.innerHTML = '<div class="p-3 text-sm text-gray-500">没有找到相关文章</div>';
      searchResults.classList.remove('hidden');
      return;
    }
    
    const html = results.map(r => {
      const item = r.item;
      return `<a href="${item.url}" class="block px-3 py-2 hover:bg-gray-50 dark:hover:bg-gray-700 border-b border-gray-100 dark:border-gray-700 last:border-0">
        <div class="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">${item.title}</div>
        <div class="text-xs text-gray-500 dark:text-gray-400 truncate mt-0.5">${item.source} · ${item.summary}</div>
      </a>`;
    }).join('');
    
    searchResults.innerHTML = html;
    searchResults.classList.remove('hidden');
  });
  
  document.addEventListener('click', (e) => {
    if (!searchInput.contains(e.target) && !searchResults.contains(e.target)) {
      searchResults.classList.add('hidden');
    }
  });
}
</script>
"""


# ---------------------------------------------------------------------------
# Tag rendering helpers
# ---------------------------------------------------------------------------

_TYPE_TAG_COLORS = {
    "干货": "bg-green-100 text-green-700 dark:bg-green-900/50 dark:text-green-300",
    "新闻": "bg-blue-100 text-blue-700 dark:bg-blue-900/50 dark:text-blue-300",
    "广告": "bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400",
    "观点": "bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300",
    "其他": "bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400",
}

_CRED_COLORS = {
    "ok": "",
    "clickbait": "text-orange-500 dark:text-orange-400",
    "exaggerated": "text-red-500 dark:text-red-400",
}

_CRED_LABELS = {
    "ok": "",
    "clickbait": "⚠️ 标题党",
    "exaggerated": "🚨 夸大",
}


def _type_tag_html(tag: str) -> str:
    color = _TYPE_TAG_COLORS.get(tag, _TYPE_TAG_COLORS["其他"])
    return f'<span class="tag-badge px-1.5 py-0.5 rounded text-xs font-medium {color}">{tag}</span>'


def _topic_tags_html(tags: List[str]) -> str:
    if not tags:
        return ""
    spans = [
        f'<span class="tag-badge px-1.5 py-0.5 rounded text-xs bg-indigo-50 text-indigo-600 dark:bg-indigo-900/40 dark:text-indigo-300">{t}</span>'
        for t in tags[:3]
    ]
    return " ".join(spans)


def _stars_html(score: int) -> str:
    score = max(0, min(3, score))
    return "⭐" * score if score > 0 else ""


def _credibility_html(cred: str, note: str) -> str:
    if cred == "ok" or not cred:
        return ""
    label = _CRED_LABELS.get(cred, cred)
    color = _CRED_COLORS.get(cred, "")
    title_attr = f' title="{note}"' if note else ""
    return f'<span class="text-xs {color}"{title_attr}>{label}</span>'


def _format_date(dt: Optional[datetime]) -> str:
    if not dt:
        return "-"
    return dt.strftime("%Y-%m-%d")


def _markdown_to_html(md: str) -> str:
    """
    Simple Markdown → HTML converter for detailed summaries.
    Handles: ## headings, ** bold **, * bullet *, > blockquote, plain text.
    """
    lines = md.split("\n")
    html_parts = []
    in_list = False

    for line in lines:
        # Heading
        h2_match = re.match(r"^## (.+)$", line)
        h3_match = re.match(r"^### (.+)$", line)
        if h2_match:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f'<h2 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mt-6 mb-2">{h2_match.group(1)}</h2>')
        elif h3_match:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append(f'<h3 class="text-base font-semibold text-gray-700 dark:text-gray-300 mt-4 mb-1">{h3_match.group(1)}</h3>')
        elif line.startswith("- ") or line.startswith("* "):
            if not in_list:
                html_parts.append('<ul class="list-disc list-inside space-y-1 text-gray-700 dark:text-gray-300 ml-2">')
                in_list = True
            item = line[2:]
            # Bold within list item
            item = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", item)
            html_parts.append(f"<li>{item}</li>")
        elif line.startswith("> "):
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line[2:])
            html_parts.append(f'<blockquote class="border-l-4 border-indigo-400 pl-4 py-1 my-2 text-gray-600 dark:text-gray-400 italic">{text}</blockquote>')
        elif line.strip() == "":
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            html_parts.append("<br>")
        else:
            if in_list:
                html_parts.append("</ul>")
                in_list = False
            text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", line)
            text = re.sub(r"`(.+?)`", r'<code class="bg-gray-100 dark:bg-gray-800 px-1 rounded text-sm">\1</code>', text)
            html_parts.append(f'<p class="text-gray-700 dark:text-gray-300 leading-relaxed">{text}</p>')

    if in_list:
        html_parts.append("</ul>")

    return "\n".join(html_parts)


# ---------------------------------------------------------------------------
# Builder class
# ---------------------------------------------------------------------------

class SiteBuilder:
    """
    Generates the complete static HTML website from the database.

    Usage:
        builder = SiteBuilder(config.site, db)
        builder.build()
    """

    def __init__(self, site_config: SiteConfig, db: Database) -> None:
        self.cfg = site_config
        self.db = db
        self.output_dir = Path(site_config.output_dir)
        self.articles_dir = self.output_dir / "articles"
        self.category_dir = self.output_dir / "category"

    def _url(self, path: str) -> str:
        """Construct a URL, using base_url if configured."""
        if self.cfg.base_url:
            return f"{self.cfg.base_url.rstrip('/')}/{path.lstrip('/')}"
        return path  # Relative path for local file:// access

    def _index_url(self, from_subdir: bool = False) -> str:
        if from_subdir:
            return "../index.html"
        return "index.html"

    def _search_json_url(self, from_subdir: bool = False) -> str:
        if from_subdir:
            return "../search.json"
        return "search.json"

    def build(self) -> None:
        """Build the complete static site."""
        logger.info("Building static site → %s", self.output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.articles_dir.mkdir(exist_ok=True)
        self.category_dir.mkdir(exist_ok=True)

        # Create placeholder .gitkeep
        (self.output_dir / ".gitkeep").touch()

        articles = self.db.get_articles(status="processed", order_by="published_at DESC")
        logger.info("Building site for %d processed articles", len(articles))

        # Build pages
        self._build_search_index(articles)
        self._build_index(articles)
        self._build_category_pages(articles)
        self._build_article_pages(articles)

        logger.info("Site build complete: %s", self.output_dir.absolute())

    def _build_search_index(self, articles: List[Article]) -> None:
        """Generate search.json for Fuse.js."""
        data = []
        for a in articles:
            topic_list = a.topic_tags_list()
            data.append({
                "id": a.id,
                "url": f"articles/{a.id}.html",
                "title": a.title,
                "summary": a.summary,
                "source": a.source,
                "type_tag": a.type_tag,
                "topic_tags": " ".join(topic_list),
                "published": _format_date(a.published_at),
            })

        search_path = self.output_dir / "search.json"
        with open(search_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        logger.debug("search.json written (%d items)", len(data))

    def _get_category_links(self, from_subdir: bool = False) -> str:
        """Generate category navigation links."""
        type_tags = self.db.get_type_tags()
        prefix = "../" if from_subdir else ""
        links = []
        for tag in type_tags:
            safe_tag = re.sub(r"[^\w\u4e00-\u9fff-]", "_", tag)
            links.append(
                f'<a href="{prefix}category/{safe_tag}.html" '
                f'class="hover:text-indigo-600 dark:hover:text-indigo-400 transition-colors">'
                f'{tag}</a>'
            )
        return "\n".join(links)

    def _render_head(
        self,
        page_title: str = "首页",
        description: str = "",
        from_subdir: bool = False,
    ) -> str:
        prefix = "../" if from_subdir else ""
        return _HEAD_TEMPLATE.format(
            lang=self.cfg.language,
            description=description or self.cfg.description,
            page_title=page_title,
            site_title=self.cfg.title,
            tailwind_cdn=_TAILWIND_CDN,
        )

    def _render_navbar(self, from_subdir: bool = False) -> str:
        return _NAVBAR_TEMPLATE.format(
            index_url=self._index_url(from_subdir),
            site_title=self.cfg.title,
            category_links=self._get_category_links(from_subdir),
        )

    def _render_footer(self, article_count: int) -> str:
        return _FOOTER_TEMPLATE.format(
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
            stats_text=f"共 {article_count} 篇文章",
        )

    def _render_scripts(self, from_subdir: bool = False) -> str:
        search_url = self._search_json_url(from_subdir)
        return (
            _THEME_SCRIPT
            + _SEARCH_SCRIPT.format(
                fuse_cdn=_FUSE_CDN,
                search_json_url=search_url,
            )
        )

    def _build_index(self, articles: List[Article]) -> None:
        """Build the main index.html."""
        stats = self.db.get_stats()

        # Stats bar
        stats_html = f"""
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
      <div class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
        <div class="text-2xl font-bold text-indigo-600 dark:text-indigo-400">{stats['processed']}</div>
        <div class="text-xs text-gray-500 mt-1">文章总数</div>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
        <div class="text-2xl font-bold text-green-600 dark:text-green-400">{len(self.db.get_sources())}</div>
        <div class="text-xs text-gray-500 mt-1">订阅来源</div>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
        <div class="text-2xl font-bold text-purple-600 dark:text-purple-400">{stats.get('feeds', 0)}</div>
        <div class="text-xs text-gray-500 mt-1">RSS 订阅</div>
      </div>
      <div class="bg-white dark:bg-gray-800 rounded-xl p-4 shadow-sm border border-gray-100 dark:border-gray-700 text-center">
        <div class="text-2xl font-bold text-orange-600 dark:text-orange-400">{datetime.now().strftime('%m-%d')}</div>
        <div class="text-xs text-gray-500 mt-1">最后更新</div>
      </div>
    </div>"""

        # Article table
        rows_html = ""
        for a in articles:
            topic_list = a.topic_tags_list()
            rows_html += f"""
      <tr class="article-row cursor-pointer" onclick="window.location='articles/{a.id}.html'">
        <td class="px-4 py-3 text-sm text-gray-500 dark:text-gray-400 whitespace-nowrap">{_format_date(a.published_at)}</td>
        <td class="px-4 py-3">
          <a href="articles/{a.id}.html" class="font-medium text-gray-900 dark:text-gray-100 hover:text-indigo-600 dark:hover:text-indigo-400 line-clamp-1 block">
            {a.title}
          </a>
          <div class="text-xs text-gray-400 dark:text-gray-500 mt-0.5 line-clamp-1">{a.summary}</div>
        </td>
        <td class="px-4 py-3 text-sm text-gray-600 dark:text-gray-400 whitespace-nowrap hidden sm:table-cell">
          <span class="truncate block max-w-24" title="{a.source}">{a.source}</span>
        </td>
        <td class="px-4 py-3 hidden md:table-cell">
          <div class="flex flex-wrap gap-1">
            {_type_tag_html(a.type_tag)}
            {_topic_tags_html(topic_list)}
          </div>
        </td>
        <td class="px-4 py-3 text-sm text-center whitespace-nowrap hidden lg:table-cell">{_stars_html(a.quality_score)}</td>
        <td class="px-4 py-3 text-sm hidden lg:table-cell">{_credibility_html(a.credibility, a.credibility_note)}</td>
        <td class="px-4 py-3 text-right">
          <a href="articles/{a.id}.html" class="text-xs text-indigo-600 dark:text-indigo-400 hover:underline whitespace-nowrap">详情 →</a>
        </td>
      </tr>"""

        table_html = f"""
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
      <div class="px-4 py-3 border-b border-gray-100 dark:border-gray-700 flex items-center justify-between">
        <h2 class="font-semibold text-gray-700 dark:text-gray-300">📋 文章列表</h2>
        <span class="text-sm text-gray-400">{len(articles)} 篇</span>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="bg-gray-50 dark:bg-gray-900/50 text-xs text-gray-500 dark:text-gray-400 uppercase tracking-wide">
              <th class="px-4 py-2 text-left font-medium">时间</th>
              <th class="px-4 py-2 text-left font-medium">标题 / 摘要</th>
              <th class="px-4 py-2 text-left font-medium hidden sm:table-cell">来源</th>
              <th class="px-4 py-2 text-left font-medium hidden md:table-cell">标签</th>
              <th class="px-4 py-2 text-center font-medium hidden lg:table-cell">质量</th>
              <th class="px-4 py-2 text-left font-medium hidden lg:table-cell">可信度</th>
              <th class="px-4 py-2 text-right font-medium">详情</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 dark:divide-gray-700">
            {rows_html}
          </tbody>
        </table>
      </div>
    </div>"""

        html = f"""
{self._render_head("知识库", from_subdir=False)}
{self._render_navbar(from_subdir=False)}

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="mb-8">
      <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">📚 我的知识库</h1>
      <p class="text-gray-500 dark:text-gray-400 mt-1 text-sm">{self.cfg.description}</p>
    </div>
    {stats_html}
    {table_html}
  </main>

{self._render_footer(len(articles))}
{self._render_scripts(from_subdir=False)}
</body>
</html>
"""

        output_path = self.output_dir / "index.html"
        output_path.write_text(html, encoding="utf-8")
        logger.info("index.html written (%d articles)", len(articles))

    def _build_category_pages(self, articles: List[Article]) -> None:
        """Build one page per type_tag category."""
        from collections import defaultdict

        by_type: dict[str, List[Article]] = defaultdict(list)
        for a in articles:
            if a.type_tag:
                by_type[a.type_tag].append(a)

        for tag, tag_articles in by_type.items():
            safe_tag = re.sub(r"[^\w\u4e00-\u9fff-]", "_", tag)
            rows_html = ""
            for a in tag_articles:
                rows_html += f"""
      <tr class="article-row cursor-pointer" onclick="window.location='../articles/{a.id}.html'">
        <td class="px-4 py-3 text-sm text-gray-500 whitespace-nowrap">{_format_date(a.published_at)}</td>
        <td class="px-4 py-3">
          <a href="../articles/{a.id}.html" class="font-medium text-gray-900 dark:text-gray-100 hover:text-indigo-600 block">{a.title}</a>
          <div class="text-xs text-gray-400 mt-0.5 line-clamp-1">{a.summary}</div>
        </td>
        <td class="px-4 py-3 text-sm text-gray-600 hidden sm:table-cell">{a.source}</td>
        <td class="px-4 py-3 text-sm text-center hidden sm:table-cell">{_stars_html(a.quality_score)}</td>
        <td class="px-4 py-3 text-right">
          <a href="../articles/{a.id}.html" class="text-xs text-indigo-600 hover:underline">详情 →</a>
        </td>
      </tr>"""

            html = f"""
{self._render_head(f"{tag} - 分类", from_subdir=True)}
{self._render_navbar(from_subdir=True)}

  <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="mb-6 flex items-center gap-3">
      <a href="../index.html" class="text-sm text-gray-500 hover:text-indigo-600">← 返回首页</a>
      <span class="text-gray-300">|</span>
      <h1 class="text-xl font-bold">{_type_tag_html(tag)} <span class="ml-1">{tag}</span></h1>
      <span class="text-sm text-gray-400">({len(tag_articles)} 篇)</span>
    </div>
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 overflow-hidden">
      <div class="overflow-x-auto">
        <table class="w-full">
          <thead>
            <tr class="bg-gray-50 dark:bg-gray-900/50 text-xs text-gray-500 uppercase tracking-wide">
              <th class="px-4 py-2 text-left">时间</th>
              <th class="px-4 py-2 text-left">标题</th>
              <th class="px-4 py-2 text-left hidden sm:table-cell">来源</th>
              <th class="px-4 py-2 text-center hidden sm:table-cell">质量</th>
              <th class="px-4 py-2 text-right">详情</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 dark:divide-gray-700">
            {rows_html}
          </tbody>
        </table>
      </div>
    </div>
  </main>

{self._render_footer(len(tag_articles))}
{self._render_scripts(from_subdir=True)}
</body>
</html>
"""
            out_path = self.category_dir / f"{safe_tag}.html"
            out_path.write_text(html, encoding="utf-8")
            logger.debug("Category page: %s (%d articles)", safe_tag, len(tag_articles))

    def _build_article_pages(self, articles: List[Article]) -> None:
        """Build individual article detail pages."""
        # Build a quick lookup for related articles
        for article in articles:
            self._build_single_article_page(article, articles)
        logger.info("Built %d article detail pages", len(articles))

    def _build_single_article_page(
        self, article: Article, all_articles: List[Article]
    ) -> None:
        """Render one article detail page."""
        topic_list = article.topic_tags_list()

        # Related articles: same type_tag or shared topic tags, max 4
        related = []
        for other in all_articles:
            if other.id == article.id:
                continue
            score = 0
            if other.type_tag == article.type_tag:
                score += 1
            other_topics = set(other.topic_tags_list())
            shared = set(topic_list) & other_topics
            score += len(shared)
            if score > 0:
                related.append((score, other))
        related.sort(key=lambda x: -x[0])
        related_articles = [r[1] for r in related[:4]]

        related_html = ""
        if related_articles:
            related_html = """
    <div class="mt-8">
      <h3 class="text-base font-semibold text-gray-700 dark:text-gray-300 mb-3">📎 相关文章</h3>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">"""
            for ra in related_articles:
                related_html += f"""
        <a href="{ra.id}.html" class="block p-3 bg-gray-50 dark:bg-gray-800 rounded-lg hover:bg-indigo-50 dark:hover:bg-indigo-900/20 border border-gray-100 dark:border-gray-700 transition-colors">
          <div class="text-sm font-medium text-gray-800 dark:text-gray-200 line-clamp-2">{ra.title}</div>
          <div class="text-xs text-gray-400 mt-1">{ra.source} · {_format_date(ra.published_at)}</div>
        </a>"""
            related_html += "\n      </div>\n    </div>"

        # Detailed summary section
        if article.detailed_summary:
            summary_content = _markdown_to_html(article.detailed_summary)
            summary_section = f"""
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-6 mt-6">
      <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-200 mb-4">🤖 AI 深度摘要</h2>
      <div class="prose dark:prose-invert max-w-none space-y-2">
        {summary_content}
      </div>
    </div>"""
        else:
            # Show generate button (for Flask UI) or note for static
            summary_section = f"""
    <div class="bg-indigo-50 dark:bg-indigo-900/20 rounded-xl border border-indigo-100 dark:border-indigo-800 p-6 mt-6 text-center">
      <div class="text-3xl mb-3">🤖</div>
      <p class="text-gray-600 dark:text-gray-400 text-sm">深度摘要将在 Web UI 中首次访问时自动生成并缓存</p>
      <a href="http://localhost:8080/articles/{article.id}" 
         class="inline-block mt-3 px-4 py-2 bg-indigo-600 text-white text-sm rounded-lg hover:bg-indigo-700 transition-colors">
        在管理界面生成摘要
      </a>
    </div>"""

        html = f"""
{self._render_head(article.title, description=article.summary, from_subdir=True)}
{self._render_navbar(from_subdir=True)}

  <main class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <!-- Breadcrumb -->
    <div class="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 mb-6">
      <a href="../index.html" class="hover:text-indigo-600 dark:hover:text-indigo-400">首页</a>
      <span>›</span>
      <span class="truncate">{article.title}</span>
    </div>

    <!-- Article header -->
    <div class="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-6">
      <div class="flex flex-wrap gap-2 mb-3">
        {_type_tag_html(article.type_tag)}
        {_topic_tags_html(topic_list)}
        {_credibility_html(article.credibility, article.credibility_note)}
      </div>
      
      <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100 leading-tight">{article.title}</h1>
      
      <div class="flex flex-wrap items-center gap-4 mt-4 text-sm text-gray-500 dark:text-gray-400">
        <span>📰 {article.source or "未知来源"}</span>
        <span>✍️ {article.author or "未知作者"}</span>
        <span>📅 {_format_date(article.published_at)}</span>
        <span>📊 {article.word_count} 字</span>
        <span>{_stars_html(article.quality_score)}</span>
      </div>

      <div class="mt-4 p-4 bg-indigo-50 dark:bg-indigo-900/20 rounded-lg border-l-4 border-indigo-400">
        <p class="text-sm font-medium text-indigo-800 dark:text-indigo-200">💡 一句话摘要</p>
        <p class="text-gray-700 dark:text-gray-300 mt-1">{article.summary}</p>
      </div>

      <div class="mt-4">
        <a href="{article.url}" target="_blank" rel="noopener noreferrer"
           class="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 dark:bg-gray-700 
                  text-gray-700 dark:text-gray-300 text-sm rounded-lg hover:bg-gray-200 
                  dark:hover:bg-gray-600 transition-colors">
          🔗 阅读原文
          <span class="text-xs text-gray-400">↗</span>
        </a>
      </div>
    </div>

    {summary_section}
    {related_html}
  </main>

{self._render_footer(0)}
{self._render_scripts(from_subdir=True)}
</body>
</html>
"""

        out_path = self.articles_dir / f"{article.id}.html"
        out_path.write_text(html, encoding="utf-8")
